#!/bin/sh

set -eu

cd "$(dirname "${0}")/../"

if [ -z "${VIRTUAL_ENV}" ]; then
    echo "Run this command from within a virtualenv"
    exit 1
fi

if ! python --version 2>&1 | grep -q "Python 3"; then
    echo "This project requires Python 3."
    exit 1
fi

echo "Installing dependencies..."
# Install requirements
pip install -r requirements.txt

echo "Bootstrap completed"
